ControleEstoque.Web/Controllers/Cadastro/CadUsuarioController.cs
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    public class CadUsuarioController : Controller
    {       
        // Abre a view com a lista acima, caso queira usar a lista.
        [Authorize]
        public ActionResult Index()
        {
            ViewBag.SenhaPadrao = VarGlobal.SenhaPadrao;
            ViewBag.PaginaAtual = VarGlobal.PaginaAtual;
            var lista = UsuarioModel.RecuperarLista(ViewBag.PaginaAtual);
            var Quant = UsuarioModel.RecuperarQuantidade();

            var difQuantPaginas = (Quant % ViewBag.QuantidadeMaxLinhaPorPagina) > 0 ? 1 : 0; //Se tiver resto joga 1
            ViewBag.QuantPaginas = difQuantPaginas + (lista.Count / ViewBag.QuantidadeMaxLinhaPorPagina); //Divide a qtde de registro somando o resto.

            return View(lista);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult UsuarioPagina(int pagina)
        {
            var lista = UsuarioModel.RecuperarLista(pagina);
            return Json(lista);
        }

        //Recupera o registro para confirmar ou excluir
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult RecuperarUsuario(int id)
        {
            return Json(UsuarioModel.RecuperarPeloId(id));
        }

        //Passa o carro no registro
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult ExcluirUsuario(int id)
        {
            return Json(UsuarioModel.ExcluirPeloId(id));
        }

        //Salva adicionando o item na lista
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult SalvarUsuario(UsuarioModel model)
        {
            string msg = GlobalMsg.RetornaMsg((int)GlobalMsg.OptionErro.OK);
            var resultado = msg;
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            //Validação
            if (!ModelState.IsValid)
            {
                msg = GlobalMsg.RetornaMsg((int)GlobalMsg.OptionErro.AVISO);
                resultado = msg;

                //lista de mensagem
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    if (model.Senha == VarGlobal.SenhaPadrao)
                    {
                        model.Senha = "";
                    }

                    //Busca o Registro
                    var id = model.Salvar();

                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        msg = GlobalMsg.RetornaMsg((int)GlobalMsg.OptionErro.ERRO);
                        resultado = msg;
                    }

                }
                catch (Exception ex)
                {
                    msg = GlobalMsg.RetornaMsg((int)GlobalMsg.OptionErro.ERRO);
                    resultado = msg;
                }
            }
            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }

    }
}

ControleEstoque.Web/Controllers/Conta/ContaController.cs
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ControleEstoque.Web.Controllers
{
    public class ContaController : Controller
    {
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginViewModel login, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(login);
            }

            var usuario = UsuarioModel.ValidarUsuario(login.Usuario, login.Senha);

            if (usuario != null)
            {
                FormsAuthentication.SetAuthCookie(usuario.Nome, login.LembrarMe);
                if (Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ModelState.AddModelError("", "Login inválido.");
            }

            return View(login);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

ControleEstoque.Web/Controllers/Grafico/GrafPerdaMesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    public class GrafPerdaMesController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

    }
}

ControleEstoque.Web/Controllers/Operacao/OpInventarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    public class OpInventarioController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
    }
}

ControleEstoque.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@{
    ViewBag.Title = "Controle de Estoque";
}
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Controle de Estoque", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Cadastros
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Grupos de produtos", "Index", "CadGrupoProduto")</li>
                                <li>@Html.ActionLink("Marcas de produtos", "Index", "CadMarcaProduto")</li>
                                <li>@Html.ActionLink("Locais de armazenamento", "Index", "CadLocalProduto")</li>
                                <li>@Html.ActionLink("Unidades de medida", "Index", "CadUnidadeMedida")</li>
                                <li>@Html.ActionLink("Produtos", "Index", "CadProduto")</li>
                                <li class="nav-divider"></li>
                                <li>@Html.ActionLink("Países", "Index", "CadPais")</li>
                                <li>@Html.ActionLink("Estados", "Index", "CadEstado")</li>
                                <li>@Html.ActionLink("Cidades", "Index", "CadCidade")</li>
                                <li>@Html.ActionLink("Fornecedores", "Index", "CadFornecedor")</li>
                                <li class="nav-divider"></li>
                                <li>@Html.ActionLink("Perfis de Usuários", "Index", "CadPerfilUsuario")</li>
                                <li>@Html.ActionLink("Usuários", "Index", "CadUsuario")</li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Operações
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Entrada de produtos", "Index", "OpEntradaEstoque")</li>
                                <li>@Html.ActionLink("Saída de produtos", "Index", "OpSaidaEstoque")</li>
                                <li>@Html.ActionLink("Lançamento de perdas de produtos", "Index", "OpLancPerdaProduto")</li>
                                <li>@Html.ActionLink("Inventário de estoque", "Index", "OpInventario")</li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Relatórios
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Posição do Estoque", "Index", "RelPosicaoEstoque")</li>
                                <li>@Html.ActionLink("Ressuprimento", "Index", "RelRessuprimento")</li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Gráficos
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Perdas por mês", "Index", "GrafPerdaMes")</li>
                                <li>@Html.ActionLink("Entradas vs saídas por mês", "Index", "GrafEntradaSaidaMesa")</li>
                            </ul>
                        </li>
                    </ul>
                    using (Html.BeginForm("LogOff", "Conta", FormMethod.Post, new { id = "logoffForm" }))
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>
                            <li><a href="#">Olá @User.Identity.Name</a></li>
                            <li><a href="javascript:document.getElementById('logoffForm').submit()">Sair</a></li>
                        </ul>
                    }
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Login", "Login", "Conta")</li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content body-imgfundo">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Controle de Estoque</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>